events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # This is for the list of public events
    path('events/', views.event_list, name='event_list'),
    path('create_event/', views.create_event, name='create_event'),
    path('events/<int:event_id>/delete/',
        views.delete_event, name='delete_event'),
    path('join_event/<int:event_id>/', views.join_event, name='join_event'),
    path('joined_events/', views.joined_events, name='joined_events'),
    path('events/<int:event_id>/enter_access_code/',
        views.enter_access_code, name='enter_access_code'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/<int:event_id>/add_comment/',
        views.add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>/',
        views.delete_comment, name='delete_comment'),
    path('events/<int:event_id>/edit/', views.edit_event, name='edit_event'),
]

postman/urls.py
from django.urls import include, re_path, path
from .views import autocomplete_recipients
from .views import (
    InboxView, SentView, ArchivesView, TrashView,
    WriteView, ReplyView, MessageView, ConversationView,
    ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView,
    IndexView
)
from . import api_urls

app_name = 'postman'
urlpatterns = [
    re_path(r'^inbox/(?:(?P<option>m)/)?$', InboxView.as_view(), name='inbox'),
    re_path(r'^sent/(?:(?P<option>m)/)?$', SentView.as_view(), name='sent'),
    re_path(r'^archives/(?:(?P<option>m)/)?$',
            ArchivesView.as_view(), name='archives'),
    re_path(r'^trash/(?:(?P<option>m)/)?$', TrashView.as_view(), name='trash'),
    re_path(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
            WriteView.as_view(), name='write'),
    re_path(r'^reply/(?P<message_id>[\d]+)/$',
            ReplyView.as_view(), name='reply'),
    re_path(r'^view/(?P<message_id>[\d]+)/$',
            MessageView.as_view(), name='view'),
    re_path(r'^view/t/(?P<thread_id>[\d]+)/$',
            ConversationView.as_view(), name='view_conversation'),
    re_path(r'^archive/$', ArchiveView.as_view(), name='archive'),
    re_path(r'^delete/$', DeleteView.as_view(), name='delete'),
    re_path(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    re_path(r'^mark-read/$', MarkReadView.as_view(), name='mark-read'),
    re_path(r'^mark-unread/$', MarkUnreadView.as_view(), name='mark-unread'),
    re_path(r'^$', IndexView.as_view()),

    re_path(r'^api/', include(api_urls)),
    re_path(r'^write/$', WriteView.as_view(), name='write'),
    re_path(r'^reply/$', ReplyView.as_view(), name='reply'),
    path('autocomplete_recipients/', autocomplete_recipients,
        name='autocomplete_recipients'),
]

varberggames/urls.py
from django.contrib import admin
from django.urls import path, include
from dal import autocomplete
from django.contrib.auth.models import User

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls'), name='profiles_urls'),
    path('accounts/', include('allauth.urls')),
    path('events/', include('events.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('postman/', include('postman.urls')),
]

postman/views.py
from urllib.parse import urlsplit, urlunsplit

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_str
from django.utils.timezone import now
from django.utils.translation import gettext as _, gettext_lazy
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView, TemplateView, View

from .fields import autocompleter_app
from .forms import WriteForm, AnonymousWriteForm, QuickReplyForm, FullReplyForm
from .models import OPTION_MESSAGES, Message, get_order_by
from .utils import format_subject, format_body
from django.contrib.auth.models import User
from django.http import JsonResponse

login_required_m = method_decorator(login_required)
csrf_protect_m = method_decorator(csrf_protect)
never_cache_m = method_decorator(never_cache)
sensitive_post_parameters_m = method_decorator(
    sensitive_post_parameters('subject', 'body'))


##########
# Helpers
##########

def autocomplete_recipients(request):
    """
    Autocompletes the recipients for a given search term.

    Args:
        request (django.http.HttpRequest): The request object containing
        the search term.

    Returns:
        django.http.JsonResponse: A JSON response containing a list of
        usernames that match the search term.
    """
    search_term = request.GET.get('term', '')
    users = User.objects.filter(
        Q(username__icontains=search_term) |
        Q(first_name__icontains=search_term) |
        Q(last_name__icontains=search_term)
    ).values_list('username', flat=True)[:10]  # Limit the results to 10

    data = list(users)
    return JsonResponse(data, safe=False)


def _get_referer(request):
    """Return the HTTP_REFERER, if existing."""
    if 'HTTP_REFERER' in request.META:
        sr = urlsplit(request.META['HTTP_REFERER'])
        return urlunsplit(('', '', sr.path, sr.query, sr.fragment))


def _get_safe_internal_url(urlstring):
    """Return the URL without the scheme part and the domain part,
    if present."""
    if urlstring:
        sr = urlsplit(urlstring)
        return urlunsplit(('', '', sr.path, sr.query, sr.fragment))


########
# Views
########
class IndexView(RedirectView):
    """
    Redirect to the inbox folder view, taking care to stay sticked to the
    targeted application instance
    when there is more than one instance.

    """
    pattern_name = 'postman:inbox'
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        """
        Get the redirect URL for the given arguments.

        Args:
            *args: The positional arguments.
            **kwargs: The keyword arguments.

        Returns:
            str: The redirect URL.

        Raises:
            NoReverseMatch: If the reverse lookup fails.
        """
        return reverse(self.pattern_name,
                       args=args, kwargs=kwargs,
                       current_app=self.request.resolver_match.namespace)


class NamespaceMixin(object):
    """Common code to manage the namespace."""

    def render_to_response(self, context, **response_kwargs):
        """
        Renders the response with a given context and additional
        response keyword arguments.

        Args:
            context (dict): The context to render the response with.
            **response_kwargs: Additional keyword arguments to pass to
                the super class's render_to_response() method.

        Returns:
            HttpResponse: The rendered response.
        """
        self.request.current_app = self.request.resolver_match.namespace
        return super().render_to_response(context, **response_kwargs)


class FolderMixin(NamespaceMixin, object):
    """Code common to the folders."""
    http_method_names = ['get']

    @never_cache_m
    @login_required_m
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Retrieves the context data for the view and adds additional
        data to it.

        Parameters:
            **kwargs (dict): Additional keyword arguments.

        Returns:
            dict: The updated context data.
        """
        context = super().get_context_data(**kwargs)
        params = {'query_dict': self.request.GET}
        option = kwargs.get('option')
        if option:
            params['option'] = option
        order_by = get_order_by(self.request.GET)
        if order_by:
            params['order_by'] = order_by
        msgs = getattr(Message.objects, self.folder_name)(
            self.request.user, **params)
        viewname = 'postman:' + self.view_name
        current_instance = self.request.resolver_match.namespace
        context.update({
            'pm_messages': msgs,
            'by_conversation': option is None,
            'by_message': option == OPTION_MESSAGES,
            'by_conversation_url':
                reverse(viewname, current_app=current_instance),
            'by_message_url': reverse(viewname, args=[OPTION_MESSAGES],
                                      current_app=current_instance),
            'current_url': self.request.get_full_path(),
            'gets': self.request.GET,
        })
        return context


class InboxView(FolderMixin, TemplateView):
    """
    Display the list of received messages for the current user.

    Optional URLconf name-based argument:
        ``option``: display option:
            OPTION_MESSAGES to view all messages
            default to None to view only the last message for each conversation
    Optional URLconf configuration attribute:
        ``template_name``: the name of the template to use

    """
    # for FolderMixin:
    folder_name = 'inbox'
    view_name = 'inbox'
    # for TemplateView:
    template_name = 'postman/inbox.html'


class SentView(FolderMixin, TemplateView):
    """
    Display the list of sent messages for the current user.

    Optional arguments and attributes: refer to InboxView.

    """
    # for FolderMixin:
    folder_name = 'sent'
    view_name = 'sent'
    # for TemplateView:
    template_name = 'postman/sent.html'


class ArchivesView(FolderMixin, TemplateView):
    """
    Display the list of archived messages for the current user.

    Optional arguments and attributes: refer to InboxView.

    """
    # for FolderMixin:
    folder_name = 'archives'
    view_name = 'archives'
    # for TemplateView:
    template_name = 'postman/archives.html'


class TrashView(FolderMixin, TemplateView):
    """
    Display the list of deleted messages for the current user.

    Optional arguments and attributes: refer to InboxView.

    """
    # for FolderMixin:
    folder_name = 'trash'
    view_name = 'trash'
    # for TemplateView:
    template_name = 'postman/trash.html'


class ComposeMixin(NamespaceMixin, object):
    """
    Code common to the write and reply views.

    Optional attributes:
        ``success_url``: where to redirect to after a successful POST
        ``user_filter``: a filter for recipients
        ``exchange_filter``: a filter for exchanges between a sender and a
        recipient
        ``max``: an upper limit for the recipients number
        ``auto_moderators``: a list of auto-moderation functions

    """
    http_method_names = ['get', 'post']
    success_url = None
    user_filter = None
    exchange_filter = None
    max = None
    auto_moderators = []

    def get_form_kwargs(self):
        """
        Returns a dictionary of keyword arguments to be passed to
        the form class.

        Returns:
            dict: A dictionary containing the keyword arguments.
        """
        kwargs = super().get_form_kwargs()
        if self.request.method == 'POST':
            kwargs.update({
                'sender': self.request.user,
                'user_filter': self.user_filter,
                'exchange_filter': self.exchange_filter,
                'max': self.max,
                'site': get_current_site(self.request),
            })
        return kwargs

    def get_success_url(self):
        return (
            _get_safe_internal_url(self.request.GET.get('next'))
            or self.success_url
            or _get_referer(self.request)
            or 'postman:inbox'
        )

    def form_valid(self, form):
        """
        Handle the form validation for the view.

        :param form: The form object that contains the data to be validated.
        :type form: Form

        :return: A redirect response to the success URL.
        :rtype: HttpResponse
        """
        params = {'auto_moderators': self.auto_moderators}
        if hasattr(self, 'parent'):  # only in the ReplyView case
            params['parent'] = self.parent
        is_successful = form.save(**params)
        if is_successful:
            messages.success(self.request, _(
                "Message successfully sent."), fail_silently=True)
        else:
            messages.warning(self.request, _(
                "Message rejected for at least one recipient."),
                fail_silently=True)
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        """
        Retrieves the context data for the view.

        :param **kwargs: Additional keyword arguments.
        :return: The updated context data.
        """
        context = super().get_context_data(**kwargs)
        context.update({
            'autocompleter_app': autocompleter_app,

postman/templates/postman/archives.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Archived Messages" %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder will never be removed. You can use this folder for long term storage." %}</p>
{% endblock %}

postman/templates/postman/base.html
{% extends "base.html" %}
{% load i18n static %}{% load postman_tags %}
{% block title %}{% trans "Messaging" %}{% endblock %}
{% block extrahead %}{{ block.super }}
<link type="text/css" media="all" rel="stylesheet" href="{% static 'postman/css/postman.css' %}">
{% endblock %}
{% block postman_menu %}
<div class="dropdown menu-button-z-index">
    <button class="btn dropdown-toggle signupbtn orange-btn position-relative menu-button-z-index" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        Menu <i class="fa-solid fa-bars"></i></button>
<ul id="postman_menu" class="dropdown-menu">{% postman_unread as unread_count %}
    <li><a class="dropdown-item postman-nav-btn orange-btn" href="{% url 'postman:inbox' %}">Inbox</a></li>
    <li><a class="dropdown-item postman-nav-btn orange-btn" href="{% url 'postman:sent' %}">Sent messages</a></li>
    <li><a class="dropdown-item postman-nav-btn orange-btn" href="{% url 'postman:write' %}">Write message</a></li>
    <li><a class="dropdown-item postman-nav-btn orange-btn" href="{% url 'postman:archives' %}">Archives</a></li>
    <li><a class="dropdown-item postman-nav-btn orange-btn" href="{% url 'postman:trash' %}">Trash</a></li>
</ul>
</div>
{% endblock %}

postman/templates/postman/base_folder.html
{% extends "postman/base.html" %}
{% load i18n postman_tags %}{% load pagination_tags %}{% comment %}
WARNING: 'pagination_tags' is a name from the dj-pagination application.
For convenience, the design of this template is done with the use of that application.
Django-postman will still be working, even if that application is not installed, by providing a mock
for the template tag library.
If the real implementation is to be used, just make sure that 'dj_pagination' is declared before 'postman'
in the INSTALLED_APPS setting.
{% endcomment %}
{% block content %}
    <div id="postman">
        <h1>{% block pm_folder_title %}{% endblock %}</h1>
        {% autopaginate pm_messages %}
        {% if invalid_page %}
            <p>{% trans "Sorry, this page number is invalid." %}</p>
        {% else %}
            {% if pm_messages %}
                {% block pm_by_modes %}<div id="pm_byModes">
                    <span class="pm_by-mode orange-btn bg-dark p-1 rounded-2">{% if by_message %}<a href="{{ by_conversation_url }}">{% endif %}{% trans "by conversation" %}{% if by_message %}</a>{% endif %}</span>
                    <span class="pm_by-mode orange-btn bg-dark p-1 rounded-2">{% if by_conversation %}<a href="{{ by_message_url }}">{% endif %}{% trans "by message" %}{% if by_conversation %}</a>{% endif %}</span>
                </div>{% endblock pm_by_modes %}
                {% for message in messages %}
                    {% if message.tags %}
                <div class="{{ message.tags }} message">
                    {% endif %}
                    {{ message }}
                </div>
                {% endfor %}
                <form action="{% block pm_form_action %}{% endblock %}" method="post">{% csrf_token %}
                    {% block pm_form_buttons %}<span id="pm_buttons">
                        {% block pm_delete_button %}<button type="submit" class="pm_btn pm_btn-delete postman-nav-btn orange-btn" id="delete-btn">{% trans 'Delete' %}</button>{% endblock %}
                        {% block pm_archive_button %}<button type="submit" class="pm_btn pm_btn-archive postman-nav-btn orange-btn" id="archive-btn">{% trans 'Archive' %}</button>{% endblock %}
                        {% block pm_undelete_button %}<button type="submit" class="pm_btn pm_btn-undelete postman-nav-btn orange-btn" id="undelete-btn">{% trans 'Undelete' %}</button>{% endblock %}
                        {% block pm_read_button %}<button type="submit" class="pm_btn pm_btn-read postman-nav-btn orange-btn" id="mark-read-btn">{% trans 'Mark as read' %}</button>{% endblock %}
                        {% block pm_unread_button %}<button type="submit" class="pm_btn pm_btn-unread postman-nav-btn orange-btn" id="mark-unread-btn">{% trans 'Mark as unread' %}</button>{% endblock %}
                    </span>{% endblock %}
                    <table id="pm_messages">
                        <thead>
                            <tr>
                                <th>{% trans 'Action' %}</th>
                                {% block pm_sender_header %} <th><a href="{% postman_order_by sender %}">{% trans 'Sender' %}</a></th>{% endblock %}
                                {% block pm_recipient_header %} <th><a href="{% postman_order_by recipient %}">{% trans 'Recipient' %}</a></th>{% endblock %}
                                <th><a href="{% postman_order_by subject %}">{% trans 'Subject' %}</a></th>
                                <th><a href="{% postman_order_by date %}">{% block pm_date %}{% trans 'Date' %}{% endblock %}</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for message in pm_messages %}
                                <tr>
                                    <td><input type="checkbox" {% if by_conversation and message.thread_id %}name="tpks" value="{{ message.thread_id }}" {% else %}name="pks" value="{{ message.pk }}" {% endif %}></td>
                                    {% block pm_sender_cell %} <td>{{ message.obfuscated_sender|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}</td>{% endblock %}
                                    {% block pm_recipient_cell %} <td>{{ message.obfuscated_recipient|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}</td>{% endblock %}
                                    <td>{% if message.is_new %}<strong>{% endif %}{% if message.is_replied %}<em>{% endif %}
                                        {% block pm_subject %}
                                            <a href="{% if by_conversation and message.thread_id %}{% url 'postman:view_conversation' message.thread_id %}{% else %}{% url 'postman:view' message.pk %}{% endif %}?next={{ current_url|urlencode }}">
                                                {% include "postman/inc_subject_ex.html" %}
                                            </a>
                                        {% endblock %}
                                        {% if message.is_replied %}</em>{% endif %}{% if message.is_new %}</strong>{% endif %}</td>
                                    <td>{{ message.sent_at|compact_date:_("g:i A,M j,n/j/y") }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </form>
                {% paginate %}
            {% else %}
                <p>{% trans "No messages." %}</p>
            {% endif %}
        {% endif %}
        {% block pm_footer_info %}{% endblock %}
    </div>
    {% block page_scripts %}
        <script>
            document.getElementById("delete-btn").addEventListener("click", function() {
                this.form.action = "{% url 'postman:delete' %}";
            });

            document.getElementById("archive-btn").addEventListener("click", function() {
                this.form.action = "{% url 'postman:archive' %}";
            });

            document.getElementById("undelete-btn").addEventListener("click", function() {
                this.form.action = "{% url 'postman:undelete' %}";
            });

            document.getElementById("mark-read-btn").addEventListener("click", function() {
                this.form.action = "{% url 'postman:mark-read' %}";
            });

            document.getElementById("mark-unread-btn").addEventListener("click", function() {
                this.form.action = "{% url 'postman:mark-unread' %}";
            });
        </script>
    {% endblock %}
{% endblock content %}

postman/templates/postman/base_write.html
{% extends "postman/base.html" %}
{% load i18n static %}
{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% if autocompleter_app.is_active %}{# using the available admin jQuery is enough #}
{# should not be necessary since AS v1.3 with AJAX_SELECT_BOOTSTRAP set #}
{#
<script type="text/javascript" src="{% static 'admin/js/jquery.min.js' %}"></script>#}
{% endif %}
{{ form.media }}{# for ajax_selects (v1.3.6 at least) #}
{% endblock %}
{% block content %}
<div id="postman">
    <form method="post" action="{% url 'postman:write' %}">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group">
                {{ form.recipients }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                {{ form.subject }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group">
                {{ form.body }}
            </div>
        </div>
        <div class="form-row">
            <input class="postman-nav-btn orange-btn" type="submit" value="Send Message">
        </div>
    </form>
</div>
{% block page_scripts %}
<script type="text/javascript">
    $(function () {
        // Initialize autocomplete
        $("#id_recipients").autocomplete({
            source: "{% url 'postman:autocomplete_recipients' %}",
            minLength: 2 // Minimum number of characters before autocomplete starts
        });
    });
</script>
{% endblock %}
{% endblock %}

postman/templates/postman/inbox.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Received Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_recipient_header %}{% endblock %}
{% block pm_date %}{% trans "Received" %}{% endblock %}
{% block pm_recipient_cell %}{% endblock %}

postman/templates/postman/inc_subject_ex.html
{% comment %}
This file is intended to be included, such as in postman/base_folder.html:
    {% include "postman/inc_subject_ex.html" %}

It provides an extended subject, as a replacement to a simple {{ message.subject }} tag.
Enhancements are:
* limit the subject length to a few words
* if there is still room up to a maximum number of words, then add the very first words of the body,
  in a grey style.

Examples:
With a total of at most 12 words, and 5 words of subject.
With body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod."

With subject: "a subject of great interest for you":
"a subject of great interest ... - Lorem ipsum dolor sit amet, consectetur ..."

With subject: "a great interest":
"a great interest - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ..."

{% endcomment %}{% load postman_tags %}{% with message.subject|truncatewords:5 as truncated_subject %}{{ truncated_subject }}
{% with truncated_subject|wordcount as subject_wc %}{% with 12|sub:subject_wc as wc %}{% if message.body and wc > 0 %} - <span style="color: grey">{{ message.body|truncatewords:wc }}</span>{% endif %}{% endwith %}{% endwith %}{% endwith %}

postman/templates/postman/reply.html
{% extends "postman/base_write.html" %}
{% load i18n %}
{% block pm_write_title %}{% trans "Reply"%}{% endblock %}
{% block pm_write_recipient %}<tr><th><label>{% trans "Recipient" %}:</label></th><td>{{ recipient }}</td></tr>{% endblock %}

postman/templates/postman/sent.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Sent Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_read_button %}{% endblock %}
{% block pm_unread_button %}{% endblock %}
{% block pm_sender_header %}{% endblock %}
{% block pm_date %}{% trans "Sent" %}{% endblock %}
{% block pm_sender_cell %}{% endblock %}

postman/templates/postman/trash.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Deleted Messages" %}{% endblock %}
{% block pm_delete_button %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_subject %}{# no link #}
     {% include "postman/inc_subject_ex.html" %}
{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder can be removed from time to time. For long term storage, use instead the archive folder." %}</p>
{% endblock %}

postman/templates/postman/view.html
{% extends "postman/base.html" %}
{% load i18n %}{% load postman_tags %}
{% block content %}
<div id="postman">
<h1>{% if pm_messages|length > 1 %}{% trans "Conversation" %}{% else %}{% trans "Message" %}{% endif %}</h1>
{% for message in pm_messages %}
<div class="pm_message{% if message.is_pending %} pm_pending{% endif %}{% if message.is_rejected %} pm_rejected{% endif %}{% if message.sender == user and message.sender_archived or message.recipient == user and message.recipient_archived %} pm_archived{% endif %}{% if message.sender == user and message.sender_deleted_at or message.recipient == user and message.recipient_deleted_at %} pm_deleted{% endif %}{% if message.recipient == user and not message.read_at %} pm_unread{% endif %}">
 <div class="pm_header">
  <span class="pm_sender">{{ message.obfuscated_sender|or_me:user }}</span> &raquo;
  <span class="pm_recipient">{{ message.obfuscated_recipient|or_me:user }}</span> |
  <span class="pm_date">{{ message.sent_at|date:"DATETIME_FORMAT"}}</span> |
  <span class="pm_subject">{{ message.subject }}</span>
{% if message.is_rejected %}  <div class="pm_status">{% trans "Rejected" %}{% if message.moderation_reason %}{% trans ":" %} {{ message.moderation_reason }}{% endif %}</div>{% endif %}
 </div>
 <div class="pm_body">{{ message.body|linebreaksbr }}</div>
</div>
{% if forloop.last %}
<form action="" method="post">{% csrf_token %}
<input type="hidden" {% if pm_messages|length > 1 and message.thread_id %}name="tpks" value="{{ message.thread_id }}"{% else %}name="pks" value="{{ message.pk }}"{% endif %}>
<a href="{{ next_url }}" class="pm_action pm_action-back">{% trans "Back" %}</a>
<span id="pm_buttons">
<button type="submit" class="pm_btn pm_btn-delete postman-nav-btn orange-btn rounded-2"
 onclick="this.form.action='{% url 'postman:delete' %}?next={{ next_url|urlencode }}'">{% trans "Delete" %}</button>
{% if not archived %}<button type="submit" class="pm_btn pm_btn-archive postman-nav-btn orange-btn rounded-2"
 onclick="this.form.action='{% url 'postman:archive' %}?next={{ next_url|urlencode }}'">{% trans "Archive" %}</button>{% endif %}
</span>
{% if reply_to_pk %}<a href="{% url 'postman:reply' reply_to_pk %}?next={{ next_url|urlencode }}"
 class="pm_action pm_action-reply">{% trans "Reply" %}</a>{% endif %}
</form>
{% if reply_to_pk %}<hr />
<h2>{% trans 'Reply' %}</h2>
<form action="{% url 'postman:reply' reply_to_pk %}?next={{ next_url|urlencode }}" method="post">{% csrf_token %}
<div id="pm_reply">{{ form.body }}</div>
<button type="submit" class="pm_btn pm_btn-reply postman-nav-btn orange-btn rounded-2">{% trans 'Reply' %}</button>
</form>{% endif %}
{% endif %}
{% endfor %}
</div>
{% endblock %}

postman/templates/postman/write.html
{% extends "postman/base_write.html" %}
{% load i18n %}
{% block pm_write_title %}{% trans "Write"%}{% endblock %}