events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # This is for the list of public events
    path('events/', views.event_list, name='event_list'),
    path('create_event/', views.create_event, name='create_event'),
    path('events/<int:event_id>/delete/',
        views.delete_event, name='delete_event'),
    path('join_event/<int:event_id>/', views.join_event, name='join_event'),
    path('joined_events/', views.joined_events, name='joined_events'),
    path('events/<int:event_id>/enter_access_code/',
        views.enter_access_code, name='enter_access_code'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/<int:event_id>/add_comment/',
        views.add_comment, name='add_comment'),
    path('delete_comment/<int:comment_id>/',
        views.delete_comment, name='delete_comment'),
    path('events/<int:event_id>/edit/', views.edit_event, name='edit_event'),
]

postman/urls.py
from django.urls import include, re_path, path
from .views import autocomplete_recipients
from .views import (
    InboxView, SentView, ArchivesView, TrashView,
    WriteView, ReplyView, MessageView, ConversationView,
    ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView,
    IndexView
)
from . import api_urls

app_name = 'postman'
urlpatterns = [
    re_path(r'^inbox/(?:(?P<option>m)/)?$', InboxView.as_view(), name='inbox'),
    re_path(r'^sent/(?:(?P<option>m)/)?$', SentView.as_view(), name='sent'),
    re_path(r'^archives/(?:(?P<option>m)/)?$',
            ArchivesView.as_view(), name='archives'),
    re_path(r'^trash/(?:(?P<option>m)/)?$', TrashView.as_view(), name='trash'),
    re_path(r'^write/(?:(?P<recipients>[^/#]+)/)?$',
            WriteView.as_view(), name='write'),
    re_path(r'^reply/(?P<message_id>[\d]+)/$',
            ReplyView.as_view(), name='reply'),
    re_path(r'^view/(?P<message_id>[\d]+)/$',
            MessageView.as_view(), name='view'),
    re_path(r'^view/t/(?P<thread_id>[\d]+)/$',
            ConversationView.as_view(), name='view_conversation'),
    re_path(r'^archive/$', ArchiveView.as_view(), name='archive'),
    re_path(r'^delete/$', DeleteView.as_view(), name='delete'),
    re_path(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    re_path(r'^mark-read/$', MarkReadView.as_view(), name='mark-read'),
    re_path(r'^mark-unread/$', MarkUnreadView.as_view(), name='mark-unread'),
    re_path(r'^$', IndexView.as_view()),

    re_path(r'^api/', include(api_urls)),
    re_path(r'^write/$', WriteView.as_view(), name='write'),
    re_path(r'^reply/$', ReplyView.as_view(), name='reply'),
    path('autocomplete_recipients/', autocomplete_recipients,
        name='autocomplete_recipients'),
]

varberggames/urls.py
from django.contrib import admin
from django.urls import path, include
from dal import autocomplete
from django.contrib.auth.models import User

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls'), name='profiles_urls'),
    path('accounts/', include('allauth.urls')),
    path('events/', include('events.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('postman/', include('postman.urls')),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import secrets
import string


class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateTimeField()
    is_private = models.BooleanField(default=False)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    participants = models.ManyToManyField(
        User, related_name='events_attending')
    access_code = models.CharField(max_length=10, null=True, blank=True)
    comments = models.ManyToManyField(
        'Comment', blank=True, related_name='event_comments')

    def has_already_passed(self):
        return self.date < timezone.now()


def generate_access_code():
    return ''.join(secrets.choice(string.digits) for _ in range(10))


class EventParticipant(models.Model):
    event = models.ForeignKey('Event', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Display part of the comment text
        return f"Comment by {self.user.username}: {self.text[:50]}"

events/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'is_private']

    def __init__(self, *args, **kwargs):
        """
        Initializes the object.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.

        Returns:
            None
        """
        super().__init__(*args, **kwargs)
        self.fields['title'].widget = forms.TextInput(
            attrs={
                'style': 'max-width: 80%',
                'placeholder': 'The title of your event'}
        )
        self.fields['description'].widget = forms.Textarea(
            attrs={
                'rows': '', 
                'cols': '', 
                'placeholder': (
                    'Describe the game/format, power-level, bring drinks, '
                    'or whatever describes the event'
                ),
                'class': 'custom-textarea',
                'style': 'max-width: 90%'
            }
        )
        self.fields['date'].widget = forms.DateTimeInput(
            attrs={
                'style': 'max-width: 80%',
                'placeholder': 'Select date and time', 
                'class': 'datetimepicker-input', 
                'id': 'datetimepicker'
            }
        )


class AccessCodeForm(forms.Form):
    access_code = forms.CharField(
        max_length=10, 
        label="Enter Access Code"
    )


class CommentForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Write your comment here...', 
                'class': 'custom-textarea'
            }
        )
    )

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event, EventParticipant, Comment
from .models import generate_access_code
from .forms import EventForm, AccessCodeForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import F
from django.urls import reverse
import string
import random
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect


@login_required
def event_list(request):
    """
    Renders a list of events.

    Parameters:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object containing the rendered events template.
    """
    if request.method == "POST":
        # Handle access code submission
        form = AccessCodeForm(request.POST)
        if form.is_valid():
            access_code = form.cleaned_data["access_code"]
            # Iterate over all events to find the matching access code
            for event in Event.objects.filter(is_private=True):
                if event.access_code == access_code:
                    # Add the user as a participant to the event
                    event.participants.add(request.user)
                    messages.success(
                        request,
                        "You have successfully joined the private event.")
                    return redirect('joined_events')

            # If no event matched the access code, display an error message
            messages.error(request, "Invalid access code. Please try again.")

    public_events = Event.objects.filter(is_private=False).order_by('date')
    return render(
        request,
        'events.html',
        {'public_events': public_events, 'form': AccessCodeForm()}
    )


@login_required
def create_event(request):
    """
    Creates an event based on the data submitted through a POST request. 

    Parameters:
        - request: The HTTP request object containing the form data.

    Returns:
        - If the event creation is successful, redirects the user to the event list page.
        - If the request method is not POST, renders the create event form.
    """
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.creator = request.user
            event.save()
            event.participants.add(request.user)
            if event.is_private:
                event.access_code = generate_access_code()
                event.save()
            messages.success(request, 'Event created successfully.')
            return redirect('event_list')
    else:
        form = EventForm()
    return render(request, 'create_event.html', {'form': form})

# Function to generate a random access code


def generate_access_code():
    """
    Generates an access code consisting of 10 random characters, including both letters (uppercase and lowercase) and digits.

    Returns:
        str: The randomly generated access code.
    """
    length = 10
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))


@login_required
def edit_event(request, event_id):
    """
    Edits an event based on the given event ID.

    Parameters:
        request (HttpRequest): The HTTP request object.
        event_id (int): The ID of the event to be edited.

    Returns:
        HttpResponse: The response containing the edited event form and event data if the user has permission to edit the event. Otherwise, redirects to the joined events page.
    """
    # Get the event by ID
    event = get_object_or_404(Event, id=event_id)

    # Checks if the logged in user is the creator of the event
    if request.user == event.creator:
        if request.method == 'POST':
            # form is filled in with the existing data
            form = EventForm(request.POST, instance=event)
            if form.is_valid():
                # Save the updated event
                form.save()
                messages.success(
                    request, "You have successfully edited the event.")
                return redirect('joined_events')
        else:
            # Display the form with existing data
            form = EventForm(instance=event)

        # Pass both the form and the event to the template
        return render(
            request, 'edit_event.html', {'form': form, 'event': event})
    else:
        messages.error(
            request, "You do not have permission to edit this event.")
        return redirect('joined_events')


@login_required
def delete_event(request, event_id):
    """
    Deletes an event.

    Parameters:
        request (HttpRequest): The HTTP request object.
        event_id (int): The ID of the event to be deleted.

    Returns:
        HttpResponseRedirect: Redirects to the 'joined_events' page.

    Raises:
        None.
    """
    # Check if the user is logged in
    if not request.user.is_authenticated:
        return redirect('login')

    # Get the event by ID
    event = get_object_or_404(Event, id=event_id)

    # Check if the user is the creator of the event
    if request.user == event.creator:
        # Delete the event
        event.delete()
    messages.success(request, "You have successfully deleted the event.")
    return redirect('joined_events')  # Redirect to the joined events page


@login_required
def join_event(request, event_id):
    """
    Adds the logged-in user to the participants of the specified event.

    Parameters:
        request (HttpRequest): The HTTP request object.
        event_id (int): The ID of the event to join.

    Returns:
        HttpResponseRedirect: A redirect to the event list page.

    Raises:
        Event.DoesNotExist: If the specified event does not exist.
    """
    event = Event.objects.get(pk=event_id)
    if request.user not in event.participants.all():
        event.participants.add(request.user)
        EventParticipant.objects.create(event=event, user=request.user)

        if request.user not in event.participants.all():
            event.participants.add(request.user)
            event.save()

        # Add a success message
        messages.success(request, "You have successfully joined the event!")

    return redirect('event_list')


def joined_events(request):
    """
    Renders a template with a list of events in which the logged-in user is a participant.

    Parameters:
        - request: The HTTP request object.

    Returns:
        - If the user is authenticated, the function renders a template 'joined_events.html' with the list of events in which the user is a participant.
        - If the user is not authenticated, the function renders a template 'joined_events.html' without any events.
    """
    if request.user.is_authenticated:
        # Filter events where the logged-in user is a participant
        user_participating_events = Event.objects.filter(
            participants=request.user)
        context = {'user_participating_events': user_participating_events}
        return render(request, 'joined_events.html', context)
    else:
        # Handle the case where the user is not authenticated
        return render(request, 'joined_events.html')


@login_required
def enter_access_code(request):
    """
    Validates and processes the access code entered by the user.

    Parameters:
        - request (HttpRequest): The HTTP request object containing
        metadata about the request.

    Returns:
        - HttpResponseRedirect: A redirect response to the 'joined_events'
        page if the access code is valid.
        - HttpResponse: A rendered HTML response displaying the 'events.html'
        template with the access code form.

    Raises:
        - None

    Description:
        - This function is decorated with the 'login_required' decorator,
        which ensures that the user must be authenticated in order to access
        this view.
        - The function first checks if the request method is 'POST'. If it is,
        it initializes an 'AccessCodeForm' object with the
        POST data and checks if the form is valid.
        - If the form is valid, it retrieves the access code entered
        by the user.
        - It then iterates over all events that have the 'is_private' flag set
        to 'True' and compares their access codes with
        the one entered by the user.
        - If a matching access code is found, the user is added as a
        participant to the event and a success message is displayed.
        The function then redirects the user to the 'joined_events' page.
        - If no event matches the access code, an error message is displayed.
        - If the request method is not 'POST', the function initializes an
        empty 'AccessCodeForm'.
        - Finally, the function renders the 'events.html' template with the
        'form' variable as context.

    Note:
        - This function assumes that the 'AccessCodeForm' and 'Event' models
        are properly defined and imported.
        - The 'messages' object is assumed to be a Django Messages Framework
        object for displaying success and error messages.
        - The 'reverse' function is assumed to be a Django utility function for
        generating URLs based on URL patterns.
    """
    if request.method == "POST":
        form = AccessCodeForm(request.POST)
        if form.is_valid():
            access_code = form.cleaned_data["access_code"]
        # Iterate over all events to find the one with the matching access code
            for event in Event.objects.filter(is_private=True):
                if event.access_code == access_code:
                    # Add the user as a participant to the event
                    event.participants.add(request.user)
                    messages.success(
                        request,

templates/base.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Magic the Gathering and Boardgame Network for Varberg in Halland, Sweden">
    <meta name="author" content="Marelius Moen">
    <title>VBG Games</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon-32x32.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Wellfleet&display=swap" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.css">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body class="d-flex h-100 text-center text-white">
    <div class="logobtn cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <div class="d-flex justify-content-between align-items-center">
            <h1><a class="logobtn orange-btn" style="display: flex;
            align-items: start;
            justify-content: start;" href="/"> VBG Games</a></h1>
            <header class="mb-auto end-0 top-0">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-between rounded-5">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse position-relative" id="navbarNav">
                        <ul class="navbar-nav">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle orange-btn" type="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        Events
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item orange-btn" href="{% url 'event_list' %}">List
                                                of events</a></li>
                                        <li><a class="dropdown-item orange-btn" href="{% url 'joined_events' %}">Joined
                                                events</a></li>
                                        <li><a class="dropdown-item orange-btn" href="{% url 'create_event' %}">Create
                                                event</a></li>
                                    </ul>
                                </div>
                            <li class="nav-item">
                                <a class="nav-link orange-btn" aria-current="page"
                                    href="{% url 'postman:inbox' %}">Messages</a>
                            </li>
                            <div class="dropdown">
                                <button class="btn dropdown-toggle orange-btn" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Marketplace
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item orange-btn" href="{% url 'product_list' %}">Items for
                                            sale</a></li>
                                    <li><a class="dropdown-item orange-btn" href="{% url 'create_product' %}">New item
                                            for sale</a></li>
                                    <li><a class="dropdown-item orange-btn" href="{% url 'your_product_list' %}">Your
                                            sale items</a></li>
                                </ul>
                            </div>
                            <li class="nav-item">
                                <a class="nav-link orange-btn" aria-current="page"
                                    href="{% url 'account_logout' %}">Logout</a>
                            </li>
                            {% else %}
                            <li class="nav-item">
                                <a class="nav-link orange-btn" aria-current="page"
                                    href="{% url 'account_signup' %}">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link orange-btn" href="{% url 'account_login' %}">Login</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </header>
        </div>
        <div class="container d-flex flex-column justify-content-center">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 bg-dark rounded-5">
                    <div style="display: flex; justify-content: center; align-items: center;">
                        <main class="text-light">
                            {% block postman_menu %}
                            {% endblock %}
                            {% block content %}
                            <!-- Content Goes here -->
                            {% endblock content %}
                        </main>
                    </div>
                </div>
            </div>
        </div>

        <footer class="mt-auto text-white-50">
            <p class="float-md-end">Made by Marelius Moen <a href="https://github.com/MareliusMoen"
                    class="text-white-50"><i class="fa-brands fa-github"></i></a> <a
                    href="https://www.linkedin.com/in/marelius-moen-067956281/" class="text-white-50"><i
                        class="fa-brands fa-linkedin"></i></a> </p>
        </footer>
    </div>

    <script
        src="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/bd589d914e.js" crossorigin="anonymous"></script>
    <!-- javascript for the django messages to dissapear automatically -->
    <script>
        $(document).ready(function () {
            // messages timeout for 10 sec 
            setTimeout(function () {
                $('.message').fadeOut('slow');
            }, 3000); // <-- time in milliseconds, 1000 =  1 sec

            // delete message
            $(document).on('click', '.del-msg', function () {
                $(this).parent().attr('style', 'display:none;');
            });
        });
    </script>
</body>

</html>

templates/create_event.html
{% extends "base.html" %}
{% if user.is_authenticated %}
{% block content %}
<h1 class="text-center">Create event</h1>

<div class="container d-flex justify-content-center align-items-center">
    <form method="post" class="create_event form-width-small-screen" id="create_event" action="{% url 'create_event' %}">
        {{ form.non_field_errors | safe }}
        {% csrf_token %}
        <div class="row g-2">
            <div class="col-12">
                <div class="form-floating form-group">
                    {{ form.title }}
                    {{ form.title.errors|safe }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating form-group form-width-small-screen">
                    {{ form.description }}
                    {{ form.description.errors|safe }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating form-group">
                    {{ form.date }}
                    {{ form.date.errors|safe }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating form-group">
                    <i class="fa-solid fa-lock"></i>  Is this a private event?
                    {{ form.is_private }}
                    {{ form.is_private.errors|safe }}
                </div>
            </div>
            <div class="align-items-center">
                {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                <button class="btn signupbtn orange-btn" type="submit"><i class="fa-solid fa-check"></i> Create event</button>
            </div>
        </div>
    </form>
</div>

{% block page_scripts %}
<!-- Format the datetimepicker -->
<script>
    $(document).ready(function () {
        $(".datetimepicker-input").datetimepicker({
            dateFormat: 'm/d/yy',
            timeFormat: 'HH:mm',
            dropdown: true,
            scrollbar: true,
            interval: 30,
        });
    });
</script>
{% endblock %}
{% endblock %}

{% endif %}

templates/edit_event.html
{% extends "base.html" %}
{% if user.is_authenticated %}
{% block content %}
<h1 class="text-center">Edit event</h1>

<div class="container d-flex justify-content-center align-items-center">
    <form method="post" class="edit_event" id="edit_event" action="{% url 'edit_event' event_id=event.id %}">
        {{ form.non_field_errors | safe }}
        {% csrf_token %}
        <div class="row g-2">
            <div class="col-12">
                <div class="form-floating form-group">
                    {{ form.title }}
                    {{ form.title.errors|safe }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating form-group">
                    {{ form.description }}
                    {{ form.description.errors|safe }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating form-group">
                    {{ form.date }}
                    {{ form.date.errors|safe }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating form-group">
                    <i class="fa-solid fa-lock"></i>  Is this a private event?
                    {{ form.is_private }}
                    {{ form.is_private.errors|safe }}
                </div>
            </div>
            <div class="align-items-center">
                {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                <button class="btn signupbtn orange-btn" type="submit"><i class="fa-solid fa-check"></i> Save changes</button>
            </div>
        </div>
    </form>
</div>

{% block page_scripts %}
<!-- Format the datetimepicker -->
<script>
    $(document).ready(function () {
        $("#datetimepicker").datetimepicker({
            dateFormat: 'm/d/yy',
            timeFormat: 'HH:mm',
            dropdown: true,
            scrollbar: true,
            interval: 30,
        });
    });
</script>
{% endblock %}
{% endblock %}

{% endif %}

templates/event_detail.html
{% extends "base.html" %}
{% if user.is_authenticated %}
{% block content %}
<!-- Event details -->
<div  class="d-flex justify-content-center flex-wrap">
<div class="w-75 mb-3 rounded-5 card-bg">
<h2>{{ event.title }}</h2>
<p>{{ event.description }}</p>
<p>{{ event.date }}</p>
<div>
    {% if user.is_authenticated and user == event.creator %}
    <a href="{% url 'edit_event' event.id %}" class="btn signupbtn orange-btn m-1 btn-sm">Edit Event</a>
    {% endif %}
</div>
</div>
</div>
{% for message in messages %}
{% if message.tags %}
<div class="{{ message.tags }} message">
    {% endif %}
    {{ message }}
</div>
{% endfor %}
<!-- Display comments -->
<h5>Comments</h5>
{% if comments %}
{% for comment in comments %}
<div class="d-flex justify-content-center flex-wrap">
    <div class="w-75 mb-3 rounded-5 ">
        <div class="card-body card-bg-opacity rounded-5">
            <p class="author-time-comment-font">{{ comment.created_at|date:"F d, Y H:i" }} By: {{ comment.user.username }}
                {% if user.is_authenticated and user == comment.user %}
                <a href="{% url 'delete_comment' comment.id %}" class="delete-comment"><i class="fa-solid fa-trash"></i></a>
                {% endif %}
            </p>
            <p class="card-text">{{ comment.text }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% else %}
<p>No comments made yet.</p>
{% endif %}
<!-- Comment form -->
<form method="post" action="{% url 'add_comment' event.id %}">
    {% csrf_token %}
    {{ comment_form.text }}
    <div>
        <button class="btn signupbtn orange-btn" type="submit">Submit</button>
    </div>
</form>
{% endblock %}
{% endif %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="justify-content-center align-items-center">
    {% if user.is_authenticated %}
    <h1>You're successfully signed in, <br>
    Welcome!</h1>
    {% else %}
    <p>Join Varberg's gaming hub! Sign up to host private or public meetups for Magic: The Gathering
        and board games.
        Explore events, message gamers, and trade cards/games in our marketplace. Get in on the action -
        create your
        account today!</p>
    <a class="signupbtn btn orange-btn" href="{% url 'account_signup' %}">Sign up here!</a>
    <a class="signupbtn btn orange-btn" href="{% url 'account_login' %}">Login</a>
    {% endif %}
</div>
{% for message in messages %}
{% if message.tags %}
<div class="{{ message.tags }} message">
{% endif %}
{{ message }}
</div>
{% endfor %}
{% endblock %}